sonar.projectKey=ssobue_consultation-record
sonar.organization=ssobue
sonar.projectName=consultation-record
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=25
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.junit.reportPaths=build/test-results/test
sonar.java.pmd.reportPaths=build/reports/pmd/main.xml,build/reports/pmd/test.xml
sonar.java.spotbugs.reportPaths=build/reports/spotbugs/main.xml,build/reports/spotbugs/test.xml
