CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(255) NOT NULL,
    role varchar(40) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'FACILITATOR', 'REVIEWER'))
);

CREATE TABLE team (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_team_name UNIQUE (name)
);

CREATE TABLE consultation_case (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL,
    facilitator_user_id bigint NOT NULL,
    title varchar(200) NOT NULL,
    status varchar(40) NOT NULL DEFAULT 'OPEN',
    purpose text,
    opened_on date NOT NULL DEFAULT CURRENT_DATE,
    closed_on date,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consultation_case_team
        FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_case_facilitator
        FOREIGN KEY (facilitator_user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_consultation_case_status
        CHECK (status IN ('OPEN', 'PAUSED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_consultation_case_closed_on
        CHECK (closed_on IS NULL OR closed_on >= opened_on)
);

CREATE TABLE problem (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consultation_case_id bigint NOT NULL,
    owner_user_id bigint,
    title varchar(200) NOT NULL,
    status varchar(40) NOT NULL DEFAULT 'OPEN',
    priority varchar(40) NOT NULL DEFAULT 'MEDIUM',
    statement text NOT NULL,
    opened_on date NOT NULL DEFAULT CURRENT_DATE,
    closed_on date,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_problem_consultation_case
        FOREIGN KEY (consultation_case_id) REFERENCES consultation_case (id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_owner
        FOREIGN KEY (owner_user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_problem_status
        CHECK (status IN ('OPEN', 'MONITORING', 'RESOLVED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_problem_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_problem_closed_on
        CHECK (closed_on IS NULL OR closed_on >= opened_on)
);

CREATE TABLE observation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL,
    author_user_id bigint,
    content text NOT NULL,
    source varchar(120),
    observed_on date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_observation_problem
        FOREIGN KEY (problem_id) REFERENCES problem (id) ON DELETE CASCADE,
    CONSTRAINT fk_observation_author
        FOREIGN KEY (author_user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE TABLE assessment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL,
    author_user_id bigint,
    hypothesis text NOT NULL,
    confidence varchar(40) NOT NULL DEFAULT 'MEDIUM',
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assessment_problem
        FOREIGN KEY (problem_id) REFERENCES problem (id) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_author
        FOREIGN KEY (author_user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_assessment_confidence
        CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE intervention (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id bigint NOT NULL,
    owner_user_id bigint,
    title varchar(200) NOT NULL,
    plan text NOT NULL,
    status varchar(40) NOT NULL DEFAULT 'PLANNED',
    planned_on date,
    completed_on date,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_intervention_problem
        FOREIGN KEY (problem_id) REFERENCES problem (id) ON DELETE CASCADE,
    CONSTRAINT fk_intervention_owner
        FOREIGN KEY (owner_user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_intervention_status
        CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED')),
    CONSTRAINT ck_intervention_completed_on
        CHECK (completed_on IS NULL OR planned_on IS NULL OR completed_on >= planned_on)
);

CREATE TABLE follow_up (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id bigint NOT NULL,
    author_user_id bigint,
    result text NOT NULL,
    next_action text,
    followed_up_on date NOT NULL DEFAULT CURRENT_DATE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_follow_up_intervention
        FOREIGN KEY (intervention_id) REFERENCES intervention (id) ON DELETE CASCADE,
    CONSTRAINT fk_follow_up_author
        FOREIGN KEY (author_user_id) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE INDEX ix_consultation_case_team_id ON consultation_case (team_id);
CREATE INDEX ix_consultation_case_facilitator_user_id ON consultation_case (facilitator_user_id);
CREATE INDEX ix_consultation_case_status ON consultation_case (status);

CREATE INDEX ix_problem_consultation_case_id ON problem (consultation_case_id);
CREATE INDEX ix_problem_owner_user_id ON problem (owner_user_id);
CREATE INDEX ix_problem_status ON problem (status);
CREATE INDEX ix_problem_priority ON problem (priority);

CREATE INDEX ix_observation_problem_id ON observation (problem_id);
CREATE INDEX ix_observation_observed_on ON observation (observed_on);

CREATE INDEX ix_assessment_problem_id ON assessment (problem_id);

CREATE INDEX ix_intervention_problem_id ON intervention (problem_id);
CREATE INDEX ix_intervention_status ON intervention (status);

CREATE INDEX ix_follow_up_intervention_id ON follow_up (intervention_id);
CREATE INDEX ix_follow_up_followed_up_on ON follow_up (followed_up_on);
